import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppProvider from "@/providers/AppProvider";
import MUIThemeProvider from "@/providers/MUIThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Event Map",
  description: "Generated by Mariam Kilany",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <MUIThemeProvider>{children}</MUIThemeProvider>
        </AppProvider>
      </body>
    </html>
  );
}
